parameter1/allured-business-media-newsletters

packages/common/components/marko.json
packages/common/components/native-x-fetch.marko
packages/common/native-x/convert-ad-to-content.js
packages/common/native-x/date-to-timestamp.js
packages/common/native-x/fetch-email-ad.js
packages/common/native-x/index.js
packages/common/native-x/is-enabled.js
packages/common/package.json
tenants/all/package.json
tenants/all/templates/blp-newsletter.marko
tenants/all/templates/components/daily-block-advertisement.marko
tenants/all/templates/components/daily-block-native-ad.marko
tenants/all/templates/ds-newsletter.marko
tenants/all/templates/me-newsletter.marko
tenants/all/templates/np-newsletter.marko

Add nativex support

---

tenants/all/config/email-x.js
tenants/all/templates/si-newsletter.marko

si-standard-newsletters

---

tenants/all/config/email-x.js
tenants/all/templates/gci-newsletter.marko

Create GCI Newsletter

---

tenants/all/config/email-x.js
tenants/all/templates/pf-newsletter.marko
tenants/all/templates/si-newsletter.marko

Create PF Newsletter

---

tenants/all/config/email-x.js
tenants/all/templates/ct-newsletter.marko
tenants/all/templates/pf-newsletter.marko
tenants/all/templates/si-newsletter.marko

Create CT Newsletter

---

tenants/all/templates/ct-product-roundup.marko
tenants/all/templates/gci-product-roundup.marko
tenants/all/templates/pf-product-roundup.marko
tenants/all/templates/si-product-roundup.marko

Create product roundup newsletter for SI, PF, GCI, and CT

Create Product Roundup Newsletters

---

tenants/all/config/email-x.js
tenants/all/templates/ct-digital-edition.marko
tenants/all/templates/gci-digital-edition.marko
tenants/all/templates/pf-digital-edition.marko
tenants/all/templates/si-digital-edition.marko

Create digital edition for CT, GCI, SI, & PF newsletters

Create Digital Edition Newsletter

---

tenants/all/config/email-x.js
tenants/all/templates/ct-breaking-news.marko
tenants/all/templates/gci-breaking-news.marko
tenants/all/templates/pf-breaking-news.marko
tenants/all/templates/si-breaking-news.marko

Create Breaking News Newsletters

---

tenants/all/config/email-x.js
tenants/all/config/native-x.js
tenants/all/templates/ct-special-edition.marko
tenants/all/templates/gci-special-edition.marko
tenants/all/templates/pf-special-edition.marko
tenants/all/templates/si-special-edition.marko

Create Special Edition Newsletters

---

tenants/all/config/email-x.js
tenants/all/config/native-x.js
tenants/all/templates/ct-newsletter-am.marko
tenants/all/templates/ct-newsletter-pm.marko
tenants/all/templates/gci-newsletter-am.marko
tenants/all/templates/gci-newsletter-pm.marko

Create CT & GCI PM Newsletter and Edit AM Newsletter Name

---

packages/common/components/dpm/content.marko
packages/common/components/dpm/marko.json
packages/common/native-x/convert-ad-to-content.js
tenants/all/templates/components/daily-block-advertisement.marko
tenants/all/templates/components/daily-block-native-ad.marko

Update dpm comments for native-x newsletter ads

---

packages/common/components/dpm/content.marko

Clean up DPM comment for Native-X

---

tenants/all/templates/components/daily-block-advertisement.marko
tenants/all/templates/components/daily-block-native-ad.marko

Pass through input.dpm to native ads

---

packages/common/components/dpm/emailx.marko

Add alt text to image of advertisements

---

tenants/all/config/email-x.js
tenants/all/templates/blp-digital-edition.marko
tenants/all/templates/blp-product-roundup.marko
tenants/all/templates/ct-breaking-news.marko
tenants/all/templates/ct-digital-edition.marko
tenants/all/templates/ct-product-roundup.marko
tenants/all/templates/ds-digital-edition.marko
tenants/all/templates/ds-product-roundup.marko
tenants/all/templates/gci-breaking-news.marko
tenants/all/templates/gci-digital-edition.marko
tenants/all/templates/gci-product-roundup.marko
tenants/all/templates/me-digital-edition.marko
tenants/all/templates/me-product-roundup.marko
tenants/all/templates/np-digital-edition.marko
tenants/all/templates/np-product-roundup.marko
tenants/all/templates/pf-breaking-news.marko
tenants/all/templates/pf-digital-edition.marko
tenants/all/templates/pf-product-roundup.marko
tenants/all/templates/si-breaking-news.marko
tenants/all/templates/si-digital-edition.marko
tenants/all/templates/si-product-roundup.marko

Create Promotion Slot

---

packages/common/components/dpm/content.marko
packages/common/native-x/convert-ad-to-content.js

Update DPM LCV for Native-X promos in newsletters.

---

packages/common/components/dpm/content.marko

Add position to DPM comment for Promotions.

---

tenants/all/templates/blp-digital-edition.marko
tenants/all/templates/blp-newsletter.marko
tenants/all/templates/blp-product-roundup.marko

New newsletter headers using the updated BLP logo. Images already uploaded to P1 S3

[DPP-4621] New Logo for BLP Newsletters

---

tenants/all/templates/ct-breaking-news.marko
tenants/all/templates/gci-breaking-news.marko
tenants/all/templates/pf-breaking-news.marko
tenants/all/templates/si-breaking-news.marko

Fix missing `get` import (resolves 502 errors)

---

tenants/all/templates/ds-digital-edition.marko
tenants/all/templates/ds-newsletter.marko
tenants/all/templates/ds-product-roundup.marko

to include the 'formerly Dayspa' tag. Images are already uploaded to P1 S3.

[DPP-4706] Updated WellSpa 360 Newsletter Header images

---

packages/common/graphql/fragments/content-list.js
tenants/all/templates/components/daily-element-content-hero.marko

Add conditional option for content-list images

---

tenants/all/templates/blp-newsletter.marko
tenants/all/templates/blp-product-roundup.marko
tenants/all/templates/ct-breaking-news.marko
tenants/all/templates/ct-newsletter-am.marko
tenants/all/templates/ct-newsletter-pm.marko
tenants/all/templates/ct-product-roundup.marko
tenants/all/templates/ct-special-edition.marko
tenants/all/templates/ds-newsletter.marko
tenants/all/templates/ds-product-roundup.marko
tenants/all/templates/gci-breaking-news.marko
tenants/all/templates/gci-newsletter-am.marko
tenants/all/templates/gci-newsletter-pm.marko
tenants/all/templates/gci-product-roundup.marko
tenants/all/templates/gci-special-edition.marko
tenants/all/templates/me-newsletter.marko
tenants/all/templates/me-product-roundup.marko
tenants/all/templates/np-newsletter.marko
tenants/all/templates/np-product-roundup.marko
tenants/all/templates/pf-breaking-news.marko
tenants/all/templates/pf-newsletter.marko
tenants/all/templates/pf-product-roundup.marko
tenants/all/templates/pf-special-edition.marko
tenants/all/templates/si-breaking-news.marko
tenants/all/templates/si-newsletter.marko
tenants/all/templates/si-product-roundup.marko
tenants/all/templates/si-special-edition.marko

Add ‘In This Issue’ block to all newsletters except digital editions

---

tenants/all/templates/wpc-product-roundup.marko

This fixes the blurriness in the original image given.

Update WPC header logo

---

tenants/all/config/core.js

Set useEmailxHref to true in dpm.emailx.

---

tenants/all/templates/wpc-product-roundup.marko

fix for size and updated version for WPC Product Roundup newsletter (already uploaded image to S3).

AF-Jun2024-Fix WPC Logo
